---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - agarzola
    assignees:
      - agarzola
    versioning-strategy: auto
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
