---
# Make eslint look no further up the project tree.
root: true

# Use the standard config.
extends: airbnb-base

# Tell eslint to account for Node.js globals.
env:
  browser: false
  node: true

ignorePatterns:
  - tests/tmp/**/*

rules:
  func-names:
    - error
    - as-needed
  import/no-dynamic-require: 0
  no-use-before-define:
    - error
    - functions: false
  no-param-reassign:
    - error
    - props: false
  no-unused-vars:
    - error
    - args: none
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
