---
name: Tests and Code Analysis
on:  # yamllint disable-line rule:truthy
  # Trigger the workflow on pushes to the primary branch and all pull requests.
  push:
    branches:
      - main
  pull_request:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Check lockfile
        uses: ChromaticHQ/javascript-lockfile-check-action@v1.2.1
        with:
          package-manager: yarn

  lint-js:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3.5.0

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3.2.4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Lint JS
        run: yarn lint

  lint-yaml:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3.1
        with:
          config_file: .yamllint.yml

  unit-tests:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    strategy:
      matrix:
        node: [14, 16, 18]
        platform: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3.5.0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3.2.4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run unit tests
        run: yarn test
